Fix/trn 123/externalise mime types
oat-sa/tao-item-runner-qti-fe pull request #176
Opened 2021-04-12 09:24 UTC by oatymart

Related to: https://oat-sa.atlassian.net/browse/TRN-123

Depends on: oat-sa/tao-core-sdk-fe#97

The module `qtiCommonRenderer/helpers/data/mimeTypes.js` was moved to `tao-core-sdk` so it can be used by both old and new test runners without creating a dependency between them.

**To test:**
`npm run test`

2021-04-13 07:24 UTC, olga-kulish approved these changes
Test succeeds, changes look good. Other than that I can't test it.
We shouldn't forget to update `package.json` before merging

2021-04-13 09:47 UTC, krampstudio requested changes
I've been able to successfully test it in Terre Deliver
Just a few cosmetic changes before approval

2021-04-13 20:31 UTC, oatymart commented on test/qtiCommonRenderer/helpers/uploadMime/test.js
> +define([
I can but I'm only following the established pattern in this repo, where no test file has a licence header.

2021-04-13 20:34 UTC, oatymart commented on test/qtiCommonRenderer/helpers/uploadMime/test.js
> +    });
Fixed.

2021-04-14 10:19 UTC, oatymart commented on src/qtiCommonRenderer/helpers/uploadMime.js
> +        return mimeTypes.getList(__);
Note: This is how I adapted this to the signature change in https://github.com/oat-sa/tao-core-sdk-fe/pull/97 (externally-provided translation function).

2021-04-14 12:24 UTC, krampstudio approved these changes
changes looks good

2021-04-14 12:39 UTC, merged