feature: TR-892 apply correct layout for RTL items in RTL tests
oat-sa/tao-item-runner-qti-fe pull request #200
Opened 2021-07-09 11:05 UTC by lecosson

**Related to:** https://oat-sa.atlassian.net/browse/TR-892

**Changes:**
- support RTL items in LTR tests

**How to check:**
- checkout necessary branch of `taoQtiItem`
- go to views dir and run `npm install` 
- register any language to check as RTL in `config/tao/client_lib_config_registry.conf.php` (en-GB  as example)
```
    'config' => array(
        'util/locale' => array(
            'decimalSeparator' => '.',
            'thousandsSeparator' => '',
            'rtl' => array(
                'ar-arb',
                'en-GB'
            )
        ),
```
- import test with pre-defined RTL language for any item
- walk trought imported test and ensure it rendered as RTL

**Requires:**
 - [ ] https://github.com/oat-sa/ ...

2021-07-12 08:06 UTC, jsconan requested changes
This is almost good. The overall idea is ok: setting the direction at rendering time. However, the place to set the attribute is not. Please see my comment below for more details.

Note: the authoring part will need a fix too, the change made here should cover both use cases.

2021-07-12 13:01 UTC, marpesia approved these changes
Works great on RTL page mode and LTR page mode. Always set the item language mode despite the page mode.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ]  Commits messages are meaningful
- [ ]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-07-12 13:15 UTC, jsconan reviewed
Looks good now. Any chance to see a unit test for it?
(see [test/runner/provider/test.js](https://github.com/oat-sa/tao-item-runner-qti-fe/blob/9a5cdce45d4e45a9bcd731b6c6e25c11704e692f/test/runner/provider/test.js))

2021-07-12 13:33 UTC, meefox approved these changes
looking good.
![Screenshot 2021-07-12 at 15 32 12](https://user-images.githubusercontent.com/2067027/125296289-6ce2d700-e326-11eb-85ca-80bc8b1f9200.png)
Agree a test would be nice for this

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-07-12 13:50 UTC, jsconan approved these changes
Looks good but it would be nice to have  unit test as well

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-07-12 13:54 UTC, jsconan requested changes
Uni tests are not running fine. Please make sure the missing util is loaded as well.

```
test/qtiCommonRenderer/interactions/extendedText/test.html
  Extended Text Interaction - plain format
    renders correctly
      Error in template rendering : locale.getLanguageDirection is not a function
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:36:24)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
      Too many calls to the `assert.async` callback
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:80:17)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:245:15
          at Function.forEach (http://127.0.0.1:56783/node_modules/lodash/lodash.js:3656:15)
      Expected 10 assertions, but 12 were run
          at http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:25:11
          at Object.execCb (http://127.0.0.1:56783/environment/require.js:1696:33)
          at Module.check (http://127.0.0.1:56783/environment/require.js:883:51)
          at Module.<anonymous> (http://127.0.0.1:56783/environment/require.js:1139:34)
          at http://127.0.0.1:56783/environment/require.js:134:23
          at http://127.0.0.1:56783/environment/require.js:1189:21
          at each (http://127.0.0.1:56783/environment/require.js:59:31)
          at Module.emit (http://127.0.0.1:56783/environment/require.js:1188:17)
    enables to input a response
      Error in template rendering : locale.getLanguageDirection is not a function
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:104:24)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
      Too many calls to the `assert.async` callback
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:122:21)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:245:15
          at Function.forEach (http://127.0.0.1:56783/node_modules/lodash/lodash.js:3656:15)
      Expected 16 assertions, but 18 were run
          at http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:86:11
          at Object.execCb (http://127.0.0.1:56783/environment/require.js:1696:33)
          at Module.check (http://127.0.0.1:56783/environment/require.js:883:51)
          at Module.<anonymous> (http://127.0.0.1:56783/environment/require.js:1139:34)
          at http://127.0.0.1:56783/environment/require.js:134:23
          at http://127.0.0.1:56783/environment/require.js:1189:21
          at each (http://127.0.0.1:56783/environment/require.js:59:31)
          at Module.emit (http://127.0.0.1:56783/environment/require.js:1188:17)
    enables to load a response[filled response]
      Error in template rendering : locale.getLanguageDirection is not a function
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:155:24)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
      Too many calls to the `assert.async` callback
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:179:17)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:245:15
          at Function.forEach (http://127.0.0.1:56783/node_modules/lodash/lodash.js:3656:15)
      Expected 5 assertions, but 7 were run
          at createTest (http://127.0.0.1:56783/environment/qunit2-parameterize.js:26:22)
          at iterateTestCases (http://127.0.0.1:56783/environment/qunit2-parameterize.js:56:6)
          at Object.test (http://127.0.0.1:56783/environment/qunit2-parameterize.js:163:5)
          at http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:144:9
          at Object.execCb (http://127.0.0.1:56783/environment/require.js:1696:33)
          at Module.check (http://127.0.0.1:56783/environment/require.js:883:51)
          at Module.<anonymous> (http://127.0.0.1:56783/environment/require.js:1139:34)
          at http://127.0.0.1:56783/environment/require.js:134:23
    enables to load a response[empty response]
      Error in template rendering : locale.getLanguageDirection is not a function
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:155:24)
          at http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:56783/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
      Too many calls to the `assert.async` callback
          at Object.<anonymous> (http://127.0.0.1:56783/test/qtiCommonRenderer/interactions/extendedText/test.js:1 [...]

2021-07-12 14:45 UTC, jsconan commented on src/runner/provider/qti.js
> +                $item.attr('dir', locale.getLanguageDirection(itemLang));
**thought:** I wonder if the language direction should not also be taken from the item attribute, as specified by the QTI standard

2021-07-23 11:13 UTC, marpesia commented
Update test issue with https://github.com/oat-sa/tao-core-sdk-fe/pull/116
Change `dir` to `itemBody` according to the Standard
![image](https://user-images.githubusercontent.com/11692751/126773948-79fec675-efc7-472f-b765-30f10ba50ded.png)

2021-08-10 06:56 UTC, jsconan commented on src/runner/provider/qti.js
> +                $itemBody.attr('dir', locale.getLanguageDirection(itemLang) || dir);
**nitpick:** While it looks ok at a first glance, the `dir` attribute should be read from the itemBody as well. And it should be forced from the language only if missing.

```suggestion
                const $item = $(elt).find('.qti-item');
                const $itemBody = $item.find('.qti-itemBody');
                const itemDir = $itemBody.attr('dir');
                if (!itemDir) {
                    const itemLang = $item.attr('lang');
                    $itemBody.attr('dir', locale.getLanguageDirection(itemLang));
                }
```

2021-09-08 09:49 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-09-08 10:20 UTC, merged