feature/TR-918/support-rtl-inline-interaction
oat-sa/tao-item-runner-qti-fe pull request #232
Opened 2021-11-24 14:30 UTC by marpesia

**Related to:** [TR-918](https://oat-sa.atlassian.net/browse/TR-918)

**Description:**

Adapt Inline text interaction to the item’s writing direction.

**Changes:**

- add direction class to the dropdown plugin

See related PR on [extension-tao-itemqti](https://github.com/oat-sa/extension-tao-itemqti/pull/1958)

2021-11-25 20:13 UTC, krampstudio requested changes
I checked the approach that seems ok for now. I have some suggestions.
Also do you mind to test it https://github.com/oat-sa/tao-item-runner-qti-fe/blob/master/test/qtiCommonRenderer/interactions/inlineChoice/test.js :smile:

2021-11-25 20:13 UTC, krampstudio commented on src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
> +        return itemDir;
niptick: add a default value to `ltr` just to be safe (in case we have an old item for example)

2021-11-25 20:13 UTC, krampstudio commented on src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
> +        let item = $container.closest('.qti-item');
```suggestion
        const item = $container.closest('.qti-item');
```

2021-11-25 20:13 UTC, krampstudio commented on src/qtiCommonRenderer/renderers/interactions/InlineChoiceInteraction.js
> +        dropdownCssClass: `qti-inlineChoiceInteraction-dropdown ${getItemDir()}`
thought: maybe it's an early optimization but you don't have to call `getItemDir` multiple times. DOM traversal like `closest` have a performance cost. I suggest you to 
```js
const dirClass = getItemDir();
$container.select2({
        width: 'element',
        placeholder: opts.placeholderText,
        minimumResultsForSearch: -1,
        containerCssClass: `${dirClass}`,
        dropdownCssClass: `qti-inlineChoiceInteraction-dropdown ${dirClass}`
 
```

2021-11-25 22:05 UTC, meefox approved these changes
Besides comments from @krampstudio 
all good, well done!

![rtl](https://user-images.githubusercontent.com/2067027/143503427-b2a2b5b1-4b21-4776-ad91-d646e80f24d3.png)
![ltr](https://user-images.githubusercontent.com/2067027/143503428-3da6f722-6714-4eaa-94a1-2942622a37d2.png)
Well done!

#
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-11-29 07:57 UTC, krampstudio commented on test/qtiCommonRenderer/interactions/inlineChoice/test.js
> +                    'the container contains an inlineChoice interaction .qti-inlineChoiceInteraction'
the message isn't accurate, it should be something like "the inline choice interaction container has the correct direction class"

2021-11-30 22:11 UTC, meefox reviewed
Checkboxes are good.
I know authoring is not a scope but I noticed the arrow is off here
![elm](https://user-images.githubusercontent.com/2067027/144136239-20212092-6864-445a-89ff-d53c47855c59.png)

2021-12-01 08:05 UTC, marpesia commented
> Checkboxes are good. I know authoring is not a scope but I noticed the arrow is off here ![elm](https://user-images.githubusercontent.com/2067027/144136239-20212092-6864-445a-89ff-d53c47855c59.png)

fixed on the extension https://github.com/oat-sa/extension-tao-itemqti/pull/1958

2021-12-01 10:06 UTC, krampstudio approved these changes
- [x] New code is covered by tests
- [x] Tests are running successfully (old and new ones) on my local machine (one test that was previously failing is still failing :confused:  )
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] <s>New code is not subject to concurrency issues (if applicable)</s>
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-12-02 13:15 UTC, merged