fix: limit IME chars on extendedText maxLength
oat-sa/tao-item-runner-qti-fe pull request #253
Opened 2022-02-16 11:41 UTC by marpesia

**Related to:** [TR-3112](https://oat-sa.atlassian.net/browse/TR-3112)

**Description:**
IME characters are not being processed well with the pattern limit. I found a [CKEditor plugin](https://github.com/w8tcha/CKEditor-wordcount-Plugin) that supports it but we can't use it because we need to have separated the counter from the input. But it's handy to check how it manages IME characters. 

**Changes:**

- Add count bytes function to check the IME characters.
- Undo characters when they reach the limit. On CKEditor and on the textarea.

**How to check:**

- Install an IME tool on your OS, and enable the Japanese keyboard to write with it.
- Test on an ExtendedText interaction with length constrain pattern.
- Check if the limit works on English and on the IME language chosen.

2022-03-02 16:35 UTC, shaveko commented
Tested on kitchen env.

Characters count are updated incorrectly in plain text input (exceeds the limit), in xhtml type the length is not limited, but the number doesn't exceed max value

https://user-images.githubusercontent.com/10635482/156405828-5fc6d3e8-cd73-46c9-aee0-e048b1325604.mp4

2022-03-03 10:43 UTC, krampstudio requested changes
I've also spotted a couple of issues:

1. In plain text mode, **without** an IME when I exceed the max number of words and hit `<Space>` the whole content is removed
![Peek 03-03-2022 11-34](https://user-images.githubusercontent.com/468620/156547696-9f7d54f7-ea71-4db6-b871-80d36c892308.gif)

2. In plain text mode, with an IME (linux) and each time I hit `<Enter>` to select the composing symbol, I get it removed. It works ok with max characters
![Peek 03-03-2022 11-37](https://user-images.githubusercontent.com/468620/156548373-7f74b823-b47a-4bd3-a26e-33aad2ba16ae.gif)

3. I was able to observe the same issue as @shaveko  with the rich text editor

2022-03-05 10:57 UTC, shaveko commented
Spotted the issue:
Chrome, English keyboard, plain text input, maxLength=5. 
Type 5 symbols, select some or whole text, type something.

Expected: text is replaced
Actual: nothing happens

2022-03-05 11:01 UTC, shaveko commented
in RichText mode when exceeding characters got cut after IME input, cursor jumps to the first symbol

Expected to keep cursor at the same place

2022-03-08 11:54 UTC, krampstudio approved these changes
The number of characters are now counted correctly.
The max length seems to work okish.
I had to fix a bug where the `editable` element was replace in the test runner by `setResponse`

- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] <s>New code is not subject to concurrency issues (if applicable)</s>
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-03-09 14:23 UTC, merged