feat: messages for choices constraints
oat-sa/tao-item-runner-qti-fe pull request #254
Opened 2022-03-09 08:24 UTC by bziondik

2022-03-16 10:51 UTC, marpesia requested changes
Great job! 
I only find one scenario that is not working as expected. Please check it :)

2022-03-16 13:49 UTC, bziondik commented on src/qtiCommonRenderer/renderers/interactions/ChoiceInteraction.js
> +    } else if (max > 1 && typeof min === 'undefined') {
fixed

2022-03-17 08:05 UTC, marpesia approved these changes
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-03-17 09:46 UTC, Silvia-loza approved these changes
All looks good and works as expected :clap:
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2022-03-23 07:23 UTC, merged