fix: add default state null for media interaction
oat-sa/tao-item-runner-qti-fe pull request #274
Opened 2022-04-28 10:56 UTC by meefox

PR template

Related to: [TR-4004](https://oat-sa.atlassian.net/browse/TR-4004)

**Description:**
Add null as the default(initial) value for media interaction to fix viewed and answered state

**Changes:**
*Changed setResponse and getResponse to fix state for media interaction on runtime.

**How to check:**
* Create items with media interaction and choices interaction.
* Add multiple (3+) previously created items to the test 
* Start the test and play media once to set the item to answer state
* Move to the next one and do not interact click next
* Observe that one item has a circle icon(answered) another has an eye icon (viewed)
* Refresh the page, observe item states should be the same

2022-04-28 12:33 UTC, jsconan requested changes
The default response is set to `{ base: null }`, and it becomes `{ integer: 1 }` once played one, then it increases with each additional try.

It looks good, except for the unit test that is failing:
```
      The default state is correct
          at Object.<anonymous> (http://127.0.0.1:50320/test/qtiCommonRenderer/interactions/media/test.js:242:24)
          at http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
          at Array.map (<anonymous>)
          at triggerHandlers (http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
          at triggerBetween (http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
          at triggerAllHandlers (http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
      The player position has changed
          at http://127.0.0.1:50320/test/qtiCommonRenderer/interactions/media/test.js:214:24
```

2022-04-28 18:39 UTC, meefox commented
> The default response is set to `{ base: null }`, and it becomes `{ integer: 1 }` once played one, then it increases with each additional try.
> 
> It looks good, except for the unit test that is failing:
> 
> ```
>       The default state is correct
>           at Object.<anonymous> (http://127.0.0.1:50320/test/qtiCommonRenderer/interactions/media/test.js:242:24)
>           at http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:310:74
>           at Array.map (<anonymous>)
>           at triggerHandlers (http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:309:34)
>           at triggerBetween (http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:285:15)
>           at triggerAllHandlers (http://127.0.0.1:50320/node_modules/@oat-sa/tao-core-sdk/dist/core/eventifier.js:262:15)
>       The player position has changed
>           at http://127.0.0.1:50320/test/qtiCommonRenderer/interactions/media/test.js:214:24
> ```

Have to modify the test and remove $play.click() due to not working and added a timeout to prevent triggering after rendering error for first 2 tests

2022-04-29 10:39 UTC, meefox commented on test/qtiCommonRenderer/interactions/media/test.js
> +    var runner;
it is not really shared it is used afterEach hook to cleanup the logic that was repeated in all case scenarios, assignment still a part of test case

2022-04-29 13:00 UTC, jsconan approved these changes

2022-05-05 08:54 UTC, merged