fix: add restrictions for input number and float
oat-sa/tao-item-runner-qti-fe pull request #307
Opened 2022-07-26 12:54 UTC by meefox

TBD

2022-07-26 13:38 UTC, shaveko commented on src/qtiCommonRenderer/renderers/interactions/TextEntryInteraction.js
> +const cleanupIntegerRegExp = new RegExp('\\D', 'g') // Remove all non-digits except the delimeter
What about e notation? like `5000` === `5e3` both are valid integers. And there is possibility to setup base, that could be 16 so `0x1A` would be also valid input for int

2022-07-26 13:39 UTC, shaveko requested changes
I don't think regex is correct approach here.. Can't we rely on parseInt / parseFloat somehow?

2022-07-27 06:32 UTC, Silvia-loza approved these changes
Fix works fine and it looks OK to me, however maybe worth to re-think a bit with @shaveko 's comments in mind...?
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2022-08-02 16:20 UTC, closed without merging

2022-08-02 16:20 UTC, meefox commented
Closed no need to merge